import { Poppins } from "next/font/google";
import "./globals.css";
import NewNavbar from "@/components/NewNavbar";


const poppins = Poppins({ subsets: ["latin"], weight:['500']})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} max-w-screen overflow-x-hidden bg-black text-white`}>
        <main className="m-auto min-h-screen flex flex-col justify-between">
          <NewNavbar/>
            {children}
        </main>
      </body>
    </html>
  );
}
